#!/usr/bin/env bash

 sudo apt-get update

 sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart